### ISSUE TITLE
ModuleNotFoundError: No module named 'od.models'; 'od' is not a package

### ISSUE THREAD

**Issue by StandGreat** [Bobo-y/flexible-yolov5#109]
在安装完requirement以后，train.py显示缺少od包，在pip install 后又显示od下没有model，想知道这个od包是作者你自己自定义的吗（或者说你自己建的），是不是和从pip上下载的不一样

**Comment by Bobo-y** [comment]
@StandGreat od 包是我自己定义的啊，所有模型代码的根目录就是od

**Comment by Bobo-y** [comment]
@StandGreat 按照README 里面那样训练，在 flexible-yolov5 下，执行 Python scripts/train.py

**Comment by StandGreat** [comment]
大师我悟了，是pycharm项目没配置好，没有把这个项目的文件夹作为根目录，而是作为了二级目录
