### ISSUE TITLE
windows下：模型和数据集的yaml文件找不到

### ISSUE THREAD

**Issue by StandGreat** [Bobo-y/flexible-yolov5#110]
![image](https://user-images.githubusercontent.com/95478133/178140721-b3378544-be33-499b-b06a-578b00d8cc57.png)

已经尝试过绝对路径，但还是找不到文件

**Comment by Bobo-y** [comment]
> ![image](https://user-images.githubusercontent.com/95478133/178140721-b3378544-be33-499b-b06a-578b00d8cc57.png)
> 
> 已经尝试过绝对路径，但还是找不到文件
抱歉，我没有Windows系统，没法复现问题

**Comment by Bobo-y** [comment]
@StandGreat 如果我没理解错的话，Windows下路径不能直接用 \, 你要么在路径开头加个 r,比如  r'XXX'

**Comment by StandGreat** [comment]
@Bobo-y 是的，在单引号前面加r确实有效！多谢！
