### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by Samuelmicer** [Bobo-y/flexible-yolov5#111]
![image](https://user-images.githubusercontent.com/28298664/178743151-0e41cd28-bf4f-4fb7-a256-8a7c6af6de0a.png)
When I try to eval my model, although the model is load to GPU, but it seems that 'model.detection.grid' and 'model.detection.anchor_grid' are still in CPU. I added a few lines of code to temporarily solve this problem
scripts/eval.py line 129: 

        model = attempt_load(weights).to(device)  # load FP32 model
        for i in range(len(model.detection.grid)):
            model.detection.grid[i] = model.detection.grid[i].to(device)
        for i in  range(len(model.detection.anchor_grid)):
            model.detection.anchor_grid[i] = model.detection.anchor_grid[i].to(device)

**Comment by Bobo-y** [comment]
@Samuelmicer thanks, It's strange. I haven't met this error.
