### ISSUE TITLE
Can't I use another pre-trained model after changing the backbone?

### ISSUE THREAD

**Issue by yuhao-q** [Bobo-y/flexible-yolov5#115]

**Comment by Bobo-y** [comment]
of course, such as hwen you use resnet-bakcbone, you can't use yolov5 pre-trained model

**Comment by yuhao-q** [comment]
Thank you for your answer. What I want to ask is, if I use swin Tiny as the backbone, can I use swin_tiny_patch4_window7_224.pth as the pretrained model, I tried it just now and found it failed

**Comment by Bobo-y** [comment]
> Thank you for your answer. What I want to ask is, if I use swin Tiny as the backbone, can I use swin_tiny_patch4_window7_224.pth as the pretrained model, I tried it just now and found it failed

yes

**Comment by Bobo-y** [comment]
i will check it
