### ISSUE TITLE
GNN is Graph Neural Network?

### ISSUE THREAD

**Issue by daiyuanm** [Bobo-y/flexible-yolov5#116]
Hello! Thanks for your work!
Is the [GNN](https://github.com/Bobo-y/flexible-yolov5/blob/v2/od/models/backbone/gnn/gnn.py) in this repository means Graph Neural Network? I am very interested in this, are there any related papers for reference? By the way, how does this GNN perform as a backbone in YOLOv5? 
Thanks a million!

**Comment by Bobo-y** [comment]
@daiyuanm yes, paper is  [Vision GNN: An Image is Worth Graph of Nodes](https://arxiv.org/abs/2206.00272)
