### ISSUE TITLE
Using EfficientNet backbone leads to precision and recall equal to zero

### ISSUE THREAD

**Issue by farzadips** [Bobo-y/flexible-yolov5#118]
Hello,
I'm using your config for defect detection task, but precision and recall are zero after training around 100 epochs,
also for predictions it can't detect any object,
I tested the same dataset for yolov5 and it worked properly.
is there sth wrong with my work?
Thanks

**Comment by Bobo-y** [comment]
@farzadips did you set nc = (your dataset class number) in configs/model_efficienet.yaml?

**Comment by farzadips** [comment]
Thanks for quick reply,
Yes, I've changed it, as you can see below,
![Capture](https://user-images.githubusercontent.com/32436413/183622647-b10772d5-a6dc-44b0-aefd-6fb166554682.PNG)

It's not just EfficientNet config but also I tried model_yolo.yaml and the same problem was consistent.

Any suggestion?

**Comment by farzadips** [comment]
@Bobo-y

**Comment by farzadips** [comment]
@Bobo-y 
I attached one more photo for more understanding of problem,
![Capture](https://user-images.githubusercontent.com/32436413/183635315-9aed25b2-c58e-4e04-8384-855e25f53842.PNG)

**Comment by Bobo-y** [comment]
@farzadips hi, your nc=1?

**Comment by farzadips** [comment]
@Bobo-y  Thanks for reply,
I already did this,
But I think the problem is not that because I tried the train_demo.ipynb for person detection which had 1 class and everything went fine,
When I change dataset to my own dataset again precision and recall stuck at 0, the task is a very small size defect detection.
I tried it before with original YoloV5 and the results were fine.
I think that the problem is for the size of annotations which is very small compared to the dataset you used.

What is your suggestion? Should I change sth like anchor size?

**Comment by farzadips** [comment]
@Bobo-y

**Comment by Bobo-y** [comment]
@farzadips can you share your dataset? According to the current description, I can't find the problem.

**Comment by farzadips** [comment]
Yes sure, can I send it via email?
If yes please share with me your email or send an email to imanpourfarzad@gmail.com .

**Comment by Bobo-y** [comment]
> Yes sure, can I send it via email? If yes please share with me your email or send an email to [imanpourfarzad@gmail.com](mailto:imanpourfarzad@gmail.com) .

hello, because your dataset is too small, and no pretrained weights, so the net can't work, I also try another backbone, P, R are still 0. To verify this, you can use the U Yolo without using pretrained weights.

**Comment by farzadips** [comment]
Hello,
I solved this problem using Imagenet pretrained weights with efficientnet and now the model is learning.

**Comment by farzadips** [comment]
@Bobo-y 
I had another question regarding using efficient backbone, if I have a pretrained model with torchvision.models.efficientnet_b0, is it possible to load those weights in this backbone?

**Comment by Bobo-y** [comment]
@farzadips  I think you just need add pretrained=True in configs/model_efficientnet.yaml
`
backbone:
  type: efficientnet
  version: b1 # b1 to b8 and l2
  pretrained: True
`

**Comment by farzadips** [comment]
Problem solved,
Thank you.
