### ISSUE TITLE
采用swin transoforme的预训练权重问题

### ISSUE THREAD

**Issue by cds221** [Bobo-y/flexible-yolov5#121]
请问您训练的swin的map精度大概是多少？
我使用swin来训练自己的数据集但是收敛的有点慢，请问可以加载官方的预训练模型吗，或者您这边可以提供预训练模型的权重吗？

**Comment by Bobo-y** [comment]
@cds221  确实慢，可以加载预训练权重，在model_swin.yaml里面的 backbone配置， pretrained=True

**Comment by cds221** [comment]
方便问下大佬最后训练出来的精度大概是多少？

**Comment by Bobo-y** [comment]
@Bobo-y 你切到main 分支里面可以看看上一个版本的，里面有对比，我当时也没用预训练权重。新版的还没训过呢

**Comment by cds221** [comment]
> @cds221 你切到main 分支里面可以看看上一个版本的，里面有对比，我当时也没用预训练权重。新版的还没训过呢

看到了，大佬再问一下你main分支中对比的都是从0开始训练的么没有使用pre-train

**Comment by Bobo-y** [comment]
> > @cds221 你切到main 分支里面可以看看上一个版本的，里面有对比，我当时也没用预训练权重。新版的还没训过呢
> 
> 看到了，大佬再问一下你main分支中对比的都是从0开始训练的么没有使用pre-train

是的，我所有的训练都没有用预训练权重

**Comment by cds221** [comment]
![image](https://user-images.githubusercontent.com/85972623/187098036-047f630e-66bd-4e13-8c4c-a11400250489.png)
大佬想问下，你改的swin是用的4，8，16来进行的下采样吗？为啥没有用8，16，32来做

**Comment by Bobo-y** [comment]
@cds221 应该是8，16，32 吧

**Comment by cds221** [comment]
大佬还想问下，swin-tiny参数量大概是在多少阿？没找到

**Comment by Bobo-y** [comment]
> 大佬还想问下，swin-tiny参数量大概是在多少阿？没找到
30691127
