### ISSUE TITLE
@Bobo-y

### ISSUE THREAD

**Issue by farzadimanpour** [Bobo-y/flexible-yolov5#123]
@Bobo-y 
Hello,
Can you explain this answer more?
Which parts should I modify? And what is your suggestion for possible modifications to have better results in the case of small object detection with this baseline?
Thanks

_Originally posted by @farzadips in https://github.com/Bobo-y/flexible-yolov5/issues/97#issuecomment-1228616426_

**Comment by Bobo-y** [comment]
@farzadimanpour OK，I'll give you a detailed answer at the weekend. I'm busy with my work. sorry

**Comment by Bobo-y** [comment]
> _Originally posted by @farzadips in [#97 (comment)](https://github.com/Bobo-y/flexible-yolov5/issues/97#issuecomment-1228616426)_

for backbone, such as YOLO backbone,  you want to detect more small object. you need output  C2
'python
def forward(self, x):
        c1 = self.C1(x)

        c2 = self.C2(c1)
        conv1 = self.conv1(c2)

        c3 = self.C3(conv1)
        conv2 = self.conv2(c3)

        c4 = self.C4(conv2)
        conv3 = self.conv3(c4)

        c5 = self.C5(conv3)
        conv4 = self.conv4(c5)

        sppf = self.sppf(conv4)

        return c2, c3, c4, sppf
'
