### ISSUE TITLE
Why is the Swin-Transformer model only outputting 2nd features onwards?

### ISSUE THREAD

**Issue by sarmientoj24** [Bobo-y/flexible-yolov5#126]
I saw this and I was wondering why it is not outputting all features.

https://github.com/Bobo-y/flexible-yolov5/blob/8f8719e58e6bf9ba0150743ba6d602c195b4234c/od/models/backbone/swin_transformer.py#L620

**Comment by sarmientoj24** [comment]
Is there a way to use all four?

**Comment by Bobo-y** [comment]
@sarmientoj24  [1:] means reutrn 2nd to last

**Comment by sarmientoj24** [comment]
so it only outputs two feature pyramids, is that what it is?

**Comment by sarmientoj24** [comment]
when i tried it it outputs this

```
swin = swin_transformer(version='tiny')
_ = swin.to('cuda')
swin_x = swin(sample)
swin_x[0].shape, swin_x[1].shape, swin_x[2].shape

(torch.Size([1, 192, 80, 80]),
 torch.Size([1, 384, 40, 40]),
 torch.Size([1, 768, 20, 20]))

```

**Comment by Bobo-y** [comment]
> when i tried it it outputs this
> 
> ```
> swin = swin_transformer(version='tiny')
> _ = swin.to('cuda')
> swin_x = swin(sample)
> swin_x[0].shape, swin_x[1].shape, swin_x[2].shape
> 
> (torch.Size([1, 192, 80, 80]),
>  torch.Size([1, 384, 40, 40]),
>  torch.Size([1, 768, 20, 20]))
> ```

what !!!!!    that a big bug, i will check it

**Comment by sarmientoj24** [comment]
thanks

**Comment by sarmientoj24** [comment]
also, is it possible to use all of the feature pyramids that it is outputting for the neck and YOLO heads?

**Comment by Bobo-y** [comment]
> also, is it possible to use all of the feature pyramids that it is outputting for the neck and YOLO heads?

of course

**Comment by Bobo-y** [comment]
> > also, is it possible to use all of the feature pyramids that it is outputting for the neck and YOLO heads?
> 
> of course

https://github.com/Bobo-y/flexible-yolov5/issues/123#issuecomment-1236325290

**Comment by Bobo-y** [comment]
> > when i tried it it outputs this
> > ```
> > swin = swin_transformer(version='tiny')
> > _ = swin.to('cuda')
> > swin_x = swin(sample)
> > swin_x[0].shape, swin_x[1].shape, swin_x[2].shape
> > 
> > (torch.Size([1, 192, 80, 80]),
> >  torch.Size([1, 384, 40, 40]),
> >  torch.Size([1, 768, 20, 20]))
> > ```
> 
> what !!!!! that a big bug, i will check it

![Uploading image.png…]()

there is no bug,  the origin outs is a list with four elements, [/4, /8, /16, /32], i only use 2nd to last

**Comment by sarmientoj24** [comment]
I think that is true. That there are 4 elements there. But this
```
 return outs[1:] 
```
just returns three which are these

```
torch.Size([24, 192, 80, 80])

torch.Size([24, 384, 40, 40])

torch.Size([24, 768, 20, 20])
```

My follow up question is why not output all of them on a forward pass? Since `torch.Size([24, 96, 160, 160])` is a large feature map. From what I know, YOLOv5 has a P6 version where it takes four feature maps. Is that for that?

**Comment by Bobo-y** [comment]
> I think that is true. That there are 4 elements there. But this
> 
> ```
>  return outs[1:] 
> ```
> 
> just returns three which are these
> 
> ```
> torch.Size([24, 192, 80, 80])
> 
> torch.Size([24, 384, 40, 40])
> 
> torch.Size([24, 768, 20, 20])
> ```
> 
> My follow up question is why not output all of them on a forward pass? Since `torch.Size([24, 96, 160, 160])` is a large feature map. From what I know, YOLOv5 has a P6 version where it takes four feature maps. Is that for that?

in this repo, only use three detection layers, so i return three. yes, P6 need four, and p7 need five
