### ISSUE TITLE
MobilenetV3主干网络中scale的作用是什么？

### ISSUE THREAD

**Issue by LaoJiuMoYang** [Bobo-y/flexible-yolov5#134]
您好，MobilenetV3中有一个supported_scale = [0.35, 0.5, 0.75, 1.0, 1.25]，这个貌似是一个比例系数，有何作用？ 是将通道数再进行缩小吗？

**Comment by Bobo-y** [comment]
> 您好，MobilenetV3中有一个supported_scale = [0.35, 0.5, 0.75, 1.0, 1.25]，这个貌似是一个比例系数，有何作用？ 是将通道数再进行缩小吗？
是的

**Comment by LaoJiuMoYang** [comment]
我这样理解不知道是否正确：在原V3的基础上，默认参数是0.5，通道数全部都缩小一半。这样对吗？   起什么作用呢，模型参数量更少，不会影响精度？

**Comment by Bobo-y** [comment]
> 我这样理解不知道是否正确：在原V3的基础上，默认参数是0.5，通道数全部都缩小一半。这样对吗？ 起什么作用呢，模型参数量更少，不会影响精度？
肯定会啊，参数越少精度会降低，但是计算量也降低了，其实理解成有很多版本的 v3 就行了

**Comment by LaoJiuMoYang** [comment]
感谢，对我的帮助很大！！！
