### ISSUE TITLE
Can add the score display for the prediction box in detector.py

### ISSUE THREAD

**Issue by songyangsun** [Bobo-y/flexible-yolov5#135]
In the past, we only can get the box by detector.py.
We can add this code to get the score display in more detail.

![add code](https://user-images.githubusercontent.com/23733567/196908098-c5c18142-af24-4f8e-869e-b297f8fbe51a.png)

We can get this:

![demo](https://user-images.githubusercontent.com/23733567/196908253-8e1a18ce-2726-45c0-b56b-5a9ca30bf92a.png)

**Comment by Bobo-y** [comment]
@songyangsun yes, you can give a PR ,so you will be a contributor

**Comment by Bobo-y** [comment]
@songyangsun  hello, can pull a new requests to v2, i merge it into main
