### ISSUE TITLE
请问模型的flops应该在哪输出

### ISSUE THREAD

**Issue by cds221** [Bobo-y/flexible-yolov5#144]
大佬，想请教下怎么能将模型的flops打印出来？

**Comment by Bobo-y** [comment]
@cds221 我没算过，要不参照一下原版的v5

**Comment by cds221** [comment]
原版的yolov5是可以直接输出的

\utils\torch_utilis.py 文件中model_info函数负责打印param和FLOPs信息，但是可能因为改变了backbone导致无法打印flops。

**Comment by Bobo-y** [comment]
@cds221 fixed
