### ISSUE TITLE
About the Resume

### ISSUE THREAD

**Issue by zhaoxixixi** [Bobo-y/flexible-yolov5#146]
作者你好，最近我在使用您的代码进行resume训练时，遇到如下相关报错：
![image](https://user-images.githubusercontent.com/66891417/230727711-bc03e046-48c8-4bc5-bbe2-2ed1e57240c5.png)
查看相关代码，原来是opt.cfg人为设置为空了。
![image](https://user-images.githubusercontent.com/66891417/230727851-4601989c-b7d9-4663-8a92-b4d9b11669c5.png)
上述代码来自./script/train.py
请问是我命令行缺失了什么参数吗？我只加入了resume参数，并将先前的pt模型导入，没有做其他修改。

**Comment by Bobo-y** [comment]
@zhaoxixixi https://github.com/Bobo-y/flexible-yolov5/commit/7234b3645bf7a2cf94b7102f267e559965eafe91 done
