### ISSUE TITLE
使用mobilenetv3作为主干网络，无法导出onnx，并且没有错误提示。

### ISSUE THREAD

**Issue by LaoJiuMoYang** [Bobo-y/flexible-yolov5#147]
作者您好，之前有提过“onnx 无法导出 F.threshold 函数，所以需要把 mobilenet SE 模块中的 HardSigmoid（） 替换掉”，能否详细解释一下如何将更换主干的网络进行导出

**Comment by Bobo-y** [comment]
@LaoJiuMoYang 你好，目前我还没有找到原因，但我试了一下可以用v1 里面的export.py 导出 mobilenet 成功，你可以试一下。需要一点改动，把attempt_load 使用v1 里面的，再把model.float().fuse() 的 fuse() 给注释掉

**Comment by Bobo-y** [comment]
懵了，我上午测试的时候确实报错了。我把代码删了重新拉下来，mobilenet 转 onnx 没问题了又

**Comment by LaoJiuMoYang** [comment]
我是使用之前版本仓库，将yolov5s.pt导出为engine成功，主干换为mobilenetv3导出为engine时失败且没有提示。奇奇怪怪

**Comment by Bobo-y** [comment]
> 我是使用之前版本仓库，将yolov5s.pt导出为engine成功，主干换为mobilenetv3导出为engine时失败且没有提示。奇奇怪怪

我这儿复现不了呢

**Comment by LaoJiuMoYang** [comment]
看了一下，之前的仓库代码和现在的没有很大的区别。我所做的仅是更改主干网络为mobilenetv3，直接去进行导出engine没有错误提示。 可能是我之前表述有误，之后我会再进行尝试，感谢回复！！！
