### ISSUE TITLE
Add True negative data to training dataset

### ISSUE THREAD

**Issue by a227799770055** [Bobo-y/flexible-yolov5#148]
想要請問，我是否可以在訓練資料中加入 true negative 的圖片，並且給它一個空白的 ground true txt 檔案？
這樣模型會將這些圖片加進去訓練嘛？

**Comment by Bobo-y** [comment]
我记得原作者回答过这个问题，会加入训练 @a227799770055

**Comment by Bobo-y** [comment]
@a227799770055 见verify_image_label这个函数，空label和missing label都会加入训练
