### ISSUE TITLE
error during compile

### ISSUE THREAD

**Issue by PraveenMNaik** [Bobo-y/flexible-yolov5#151]
Following error observed during compile, can you please address
Traceback (most recent call last):
  File "/home3/REPOSITORIES/flexible-yolov5-2/scripts/train.py", line 39, in <module>
    import eval  # for end-of-epoch mAP
  File "/home3/REPOSITORIES/flexible-yolov5-2/scripts/eval.py", line 26, in <module>
    from od.models.modules.experimental import attempt_load
ModuleNotFoundError: No module named 'od'

**Comment by Bobo-y** [comment]
@PraveenMNaik hi, you should cd in  /home3/REPOSITORIES/flexible-yolov5-2, and then run command

**Comment by PraveenMNaik** [comment]
Thank you... agai followig error:
Traceback (most recent call last):
  File "scripts/train.py", line 24, in <module>
    from od.models.modules.experimental import attempt_load
  File "/home3/207it001/REPOSITORIES/yolov5-flexible/od/__init__.py", line 1, in <module>
    from .models import Model, ComputeLoss
  File "/home3/207it001/REPOSITORIES/yolov5-flexible/od/models/__init__.py", line 1, in <module>
    from .model import Model
  File "/home3/207it001/REPOSITORIES/yolov5-flexible/od/models/model.py", line 2, in <module>
    from addict import Dict
ModuleNotFoundError: No module named 'addict'


please reply

**Comment by Bobo-y** [comment]
pip install addict

**Comment by PraveenMNaik** [comment]
Following multiple type error occurs:
Traceback (most recent call last):
  File "/home3/.local/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 36, in __del__
  File "/home3/.local/lib/python3.8/site-packages/torch/storage.py", line 520, in _free_weak_ref
AttributeError: 'NoneType' object has no attribute '_free_weak_ref'

Reply please....

**Comment by PraveenMNaik** [comment]
**I tried all possible ways.... even in colab environment when tried improper installation occured with following installation on run with requirement file....**

Building wheels for collected packages: scikit-learn
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for scikit-learn (setup.py) ... error
  ERROR: Failed building wheel for scikit-learn
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
ERROR: Could not build wheels for scikit-learn, which is required to install pyproject.toml-based projects

**Comment by PraveenMNaik** [comment]
Can you please run it again from youe end and verify the code validity,,,, if works well kindly share the colab file to my mail id....

**Comment by PraveenMNaik** [comment]
Sir, i could be able to fix all issues .... but struck with the following issue... pls help resolving it...

RuntimeError: CUDA error: out of memory
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.

But, my GPU is quite good to handle ... i even tried for 1 batch size.... pls suggest.... however VGG and Mobilenet worked when PANET was kept ... why does it consume so much GPU....

**Comment by Bobo-y** [comment]
> Sir, i could be able to fix all issues .... but struck with the following issue... pls help resolving it...
> 
> RuntimeError: CUDA error: out of memory CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> 
> But, my GPU is quite good to handle ... i even tried for 1 batch size.... pls suggest.... however VGG and Mobilenet worked when PANET was kept ... why does it consume so much GPU....

i need know your model config

**Comment by PraveenMNaik** [comment]
Sir, as suggested in Readme file i used the following configuration  for run

python scripts/train.py  --batch 16 --epochs 5 --data configs/data.yaml --cfg configs/model_XXX.yaml


Replaced data.yaml with my custom data file.... and experimented with all models defined under config/ <<vgg, mobilenet>> etc.. i didnt change anything

**Comment by Bobo-y** [comment]
> But, my GPU is quite good to handle ... i even tried for 1 batch size.... pls suggest.... however VGG and Mobilenet worked when PANET was kept ... why does it consume so much GPU....

do you mean vgg and mobilenet can work good? I want to konw which model casue CUDA error: out of memory.  transformer backbone or  gnn?

**Comment by PraveenMNaik** [comment]
@Bobo-y yeah...for vgg and mobilenet no problem it runs fine.... however for rest of the models defined in your repo it crashes giving CUDA error. I found to have more GPU is considered for vgg and mobilenet as well.... kindly suggest if any modifications needed to updtae before train...I didn't use transformer backbone or gnn as well...

**Comment by Bobo-y** [comment]
> @Bobo-y yeah...for vgg and mobilenet no problem it runs fine.... however for rest of the models defined in your repo it crashes giving CUDA error. I found to have more GPU is considered for vgg and mobilenet as well.... kindly suggest if any modifications needed to updtae before train...I didn't use transformer backbone or gnn as well...

It's not easy to find a problem with this. What type of  your  GPU? Normally, yolo-s and resnet-18 should be able to run

**Comment by PraveenMNaik** [comment]
my GPU is  NVIDIA Tesla M40 GPUs with GM200 graphics processors.... 
i just used this configuration
python scripts/train.py --batch 16 --epochs 5 --data configs/data.yaml --cfg configs/model_XXX.yaml... is there any changes to be done before run

**Comment by Bobo-y** [comment]
> @Bobo-y yeah...for vgg and mobilenet no problem it runs fine.... however for rest of the models defined in your repo it crashes giving CUDA error. I found to have more GPU is considered for vgg and mobilenet as well.... kindly suggest if any modifications needed to updtae before train...I didn't use transformer backbone or gnn as well...

It's not easy to find a problem with this. What type of  your  GPU? Normally, yolo-s and resnet-18 should be able to run

**Comment by Bobo-y** [comment]
i think this error caused by your env, may be gpu
