### ISSUE TITLE
Drop layer

### ISSUE THREAD

**Issue by ratom** [Bobo-y/flexible-yolov5#153]
I want to drop three layers at one time and keep only one layer of the resnet50.  Or if I want to keep two of any layers and remove any two , how can I do this. Can I do to use only first layer. 
def resnet50(pretrained=False, **kwargs):
    """Constructs a ResNet-50 model.
    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
    """
    model = Resnet(Bottleneck, [3, 0, 0, 0], **kwargs)
    if pretrained:
        model.load_state_dict(model_zoo.load_url(model_urls['resnet50'], model_dir='.'), strict=False)
    return model

**Comment by Bobo-y** [comment]
![image](https://github.com/Bobo-y/flexible-yolov5/assets/9928596/cf4aad4a-dfde-490c-92ad-c1f34b8ece68)
 
model = Resnet(Bottleneck, [3, 0, 0, 0], **kwargs)  ,you will remove self.layer2, self.layer3, self.layer4, but  you must rewrite forward func.

you want keep two of any layers,i think not right, such as keep layer1 and layer3, the output of layer1 can't feed in layer3
