### ISSUE TITLE
repvgg做为backbone时，保存的pt模型是多分支结构还是单路结构？

### ISSUE THREAD

**Issue by wjli-debug** [Bobo-y/flexible-yolov5#156]

**Comment by wjli-debug** [comment]
repvgg做为backbone时，保存的pt模型是多分支结构还是单路结构？因为repvgg在训练的时候多采用多分支，但是在推理阶段使用单路提升推理速度，那么保存的pt模型是多分支结构还是单路结构？

**Comment by Bobo-y** [comment]
看看有没有走重参数化吧

**Comment by wjli-debug** [comment]
backbone使用的是默认提供的repvgg

**Comment by wjli-debug** [comment]
是看deploy参数吗？

**Comment by Bobo-y** [comment]
> 是看deploy参数吗？

是的，我看了一下，repvgg 都是保存啥的都是带分支的，这个仓库没有使用重参数化，后来没有去修改过了
