### ISSUE TITLE
与官网对比的速度问题

### ISSUE THREAD

**Issue by hyg1314520** [Bobo-y/flexible-yolov5#88]
我在使用该代码和官方代码对比时候，我发现您的代码比官方的代码速度快上很多，同样的RSOD数据集下，在该代码下一个epoch为33s，但是在官方的代码上v6.1，速度为1min16s，请问这是哪里的问题呢，我发现该代码下训练时，gpu利用率一直很高，但是官网的有时候高有时候低

**Comment by yl305237731** [comment]
@hyg1314520 这个应该不会吧，和官方应该是一样的呢，没太注意这个
