### ISSUE TITLE
运行trt_infer.py不会生成结果图片吗？

### ISSUE THREAD

**Issue by QinganZhang** [Bobo-y/flexible-yolov5#89]
![image](https://user-images.githubusercontent.com/72648020/165981157-c1776597-c3a7-4b2a-92bf-bda9ce7e473c.png)
![image](https://user-images.githubusercontent.com/72648020/165984304-cd3edda0-f825-444e-9d0e-c286bcca1b6c.png)
![image](https://user-images.githubusercontent.com/72648020/165987001-a5b69f05-5aab-4b95-8a44-974d1ebb6fcb.png)

@yl305237731 
问题：打印出trt_infer.py main中bboxes = yolov5_wrapper.infer(img)的bboxes，每个bbox是一个六个元素的tensor，不太懂代表什么意思，与detector.py中140行 `bboxes, scores, ids = model.detect_image(im)`中bboxes不同 ，自己初学，希望多多指教，十分感谢！

之前的命令
使用的是https://pan.baidu.com/s/1Mc1J4t03qrslj1mywaWqBw 的权重，

1. `python scripts/detector.py --pt_path pt_model/yolos.pt --imgs_root images/imgs --save_dir images/tmp/`使用detector.py进行测试，可以得到正确的带框的测试图片

2. `python scripts/deploy/export.py --weights pt_model/yolos.pt`导出为onnx模型

3. `python scripts/trt_quant/convert_trt_quant.py --img-dir ../my_yolo_data/images/train/ --onnx-model onnx_model/yolos.onnx`导出为trt文件

4. `python scripts/trt_quant/trt_infer.py --engine-file-path trt_model/yolo_model.trt --img-path images/imgs/person.jpg`使用导出的trt文件进行推理

**Comment by yl305237731** [comment]
@QinganZhang 只推理了，没有往图片上画框，需要自己加。返回的是bbox [xmin, ymin, max, ymax, conf, class], 从打印的值来看，不太对

**Comment by QinganZhang** [comment]
由于自己初学TensorRT，而且由于目标检测模型细节比较多，代码量比较大，关于您的这个项目我有一些地方不是很明白，希望得到您的指点，不知道能否留一个微信呢？我昨天晚上给您发了邮件，具体您可以查看您的bjtu邮箱，十分感谢！ @yl305237731
