### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by lisheng98** [Bobo-y/flexible-yolov5#90]
I got these kind of error that the train.py file cannot detect files in utils. I did not move any of the files around. Can anyone suggest how to fix it?

![image](https://user-images.githubusercontent.com/75806366/166113643-4ce3f839-b989-4ee0-8101-890a48b09e13.png)

![image](https://user-images.githubusercontent.com/75806366/166113737-402c712f-64cf-4b57-b6d7-3be9b58c41b6.png)

**Comment by yl305237731** [comment]
@lisheng98 不要去加载原作者的模型权重

**Comment by lisheng98** [comment]
May I know how to use the weight to visualise on a single image?

**Comment by Bobo-y** [comment]
@lisheng98 see scripts/detector.py
