### ISSUE TITLE
please add od/models/modules/LinearScheduler class source

### ISSUE THREAD

**Issue by veveup** [Bobo-y/flexible-yolov5#91]

**Comment by tengyunlai** [comment]
should be this:
`
import numpy as np
from torch import nn


class LinearScheduler(nn.Module):
    def __init__(self, dropblock, start_value, stop_value, nr_steps):
        super(LinearScheduler, self).__init__()
        self.dropblock = dropblock
        self.i = 0
        self.drop_values = np.linspace(start=start_value, stop=stop_value, num=int(nr_steps))

    def forward(self, x):
        return self.dropblock(x)

    def step(self):
        if self.i < len(self.drop_values):
            self.dropblock.drop_prob = self.drop_values[self.i]

        self.i += 1
`

**Comment by Bobo-y** [comment]
@veveup done
