### ISSUE TITLE
使用hrnet18预训练权重报错问题

### ISSUE THREAD

**Issue by jhygithub123** [Bobo-y/flexible-yolov5#93]
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for detection.m.0.weight: copying a param with shape torch.Size([255, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([27, 128, 1, 1]).
        size mismatch for detection.m.0.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([27]).
        size mismatch for detection.m.1.weight: copying a param with shape torch.Size([255, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([27, 256, 1, 1]).
        size mismatch for detection.m.1.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([27]).
        size mismatch for detection.m.2.weight: copying a param with shape torch.Size([255, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([27, 512, 1, 1]).
        size mismatch for detection.m.2.bias: copying a param with shape torch.Size([255]) from checkpoint, the shape in current model is torch.Size([27]).

**Comment by Bobo-y** [comment]
好的，有空看看，当时一起传的，可能传混淆了

**Comment by jhygithub123** [comment]
> 好的，有空看看，当时一起传的，可能传混淆

您好，我在使用efficientnet权重的时候也出现了这个问题，我使用的平台是colab，是预训练权重的问题还是我的问题呢。

**Comment by Bobo-y** [comment]
> > 好的，有空看看，当时一起传的，可能传混淆
> 
> 您好，我在使用efficientnet权重的时候也出现了这个问题，我使用的平台是colab，是预训练权重的问题还是我的问题呢。

匹配不上一般是我这边的问题，我check一下训练代码和仓库代码

**Comment by xiaoboyang2333** [comment]
我在训练swin_tiny时也遇到了这个问题，预训练权重和自己的数据集无法匹配

**Comment by Bobo-y** [comment]
@xiaoboyang2333 @jhygithub123 我测试了一下，报这个错是因为检测的类别不一样导致的，https://blog.csdn.net/hxxjxw/article/details/119491163
