### ISSUE TITLE
请问是基于yolov5哪个版本的哇？

### ISSUE THREAD

**Issue by LinB203** [Bobo-y/flexible-yolov5#94]
您好，感谢带来这么好的代码，我也有改backbone的需求，但注意到您的代码的时间和最新的yolov5 6.1版本发布的时间有些久远，所以我想问下您的代码是基于yolov5的哪个版本，或者说哪个时间段发布的yolov5哇？
另外您的yolov5s的ap不到0.5，而官方的代码给出的ap是56.8，这是为什么呢！希望得到解答！谢谢！

**Comment by Bobo-y** [comment]
挺早的版本了，应该是5。0吧

**Comment by cds221** [comment]
现在代码版本有更新了吗感觉像yolo6.1了
