### ISSUE TITLE
如何添加FPN层以实现更好的小目标检出

### ISSUE THREAD

**Issue by cydiachen** [Bobo-y/flexible-yolov5#97]
Hello，你的工作太完美了。我觉得是一个绝佳的Yolo v5 baseline；有一个小问题想要和你请教：请问这份代码库如何添加FPN层的P2层使得网络对于小目标的检出更好呢

**Comment by Bobo-y** [comment]
@cydiachen 在backbone上增加一个C2输出，在FPN里面将P3上采样和C2 concat 得到P2层，再在PAN里面从P2开始下采样，对于检测头，将 strides, anchors, ch 改成对应的4个即可

**Comment by farzadips** [comment]
Hello,
Can you explain this answer more?
Which parts should I modify?
Thanks
